### ISSUE TITLE
Credential helper no longer renews the crendetial

### ISSUE THREAD

**Issue by shizhMSFT** [Azure/acr-docker-credential-helper#32]
The credential helper no longer renews the credential since there is no `tenant` and `credential` in the `refresh_token` returned by `az acr login`.

It is an regression caused by https://github.com/Azure/azure-cli/pull/6211

**Comment by djyou** [comment]
The CLI change is on purpose since there are a few cases (MSI, SP+Cert) where obtaining refresh token is not possible (see comment https://github.com/Azure/azure-cli/pull/6211#issuecomment-384467696).

Alternative approaches:

 - If persistent credentials are needed, use admin user credentials or SP. SP might be preferred since you can restrict access by assigning different roles.
 - Run `az acr login` before docker operations.

Closing this issue here.

**Comment by josegonzalez** [comment]
Given that the credential helper doesn't actually renew credentials, what is the point of this repository?
